# Generated by Django 4.2 on 2023-05-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField()),
                ('created', models.TimeField()),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
